# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='graduation_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='graduation_year',
            field=models.IntegerField(choices=[(1, '2007'), (2, '2008'), (3, '2009'), (4, '2010'), (5, '2011'), (6, '2012'), (7, '2013'), (8, '2014'), (9, '2015'), (10, '2016'), (11, '2017'), (12, '2018')], default=1900),
        ),
    ]
